### PR TITLE
wslsys: Increase speed of registry queries

### LINKED ISSUE #84: Performance issue due to usage of Powershell
**Background Information:**
 - Build: 18362 (19h1_release)
 - WSL: Ubuntu 18.04.2 LTS (Ubuntu in Store)
 - Version: wslu 2.0.0, wslfetch v38

**Describe the bug**
wslfetch takes a long time to display output (I've seen it vary between 7 and 15 seconds). wslsys takes 1.5-3 seconds itself.

**To Reproduce**
Steps to reproduce the behavior: Just run wslfetch with no parameters (same for wslsys)

**Expected behavior**
The output should appear more quickly.

**Additional context**
I initially suspected that it was Powershell being slow but I can't seem to get it to show in my task manager so I may be wrong. You don't call it THAT many times do you?

I will also investigate on a solution myself.

### PR DESCRIPTION
**Pull request by paulstelian97**
I have used regular `reg query` commands instead of Powershell to get the registry values for wslsys.

## Description
On my system, Powershell takes a good deal of time (0.5 seconds or more) to load. Take that 4 times for wslsys, that means 2 seconds. Take that times 4 (I think even more) in wslfetch, we get to 10 or more seconds. My approach, using `reg query` commands which are faster, considerably helps alleviate this issue.

Fixes #84.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have read Code of Conduct and Contributing documentations.
- [ ] My code follows the code style of this project.

### CODE REVIEW

File: src/wslsys.sh [hunk 1]
```diff
@@ -3,10 +3,14 @@ version="28"
 help_short="wslsys (-h|-v|-S|-U|-b|-B|-fB|-R|-K|-P) -s"
 
 ## Windows 10 information
-branch=$(winps_exec "(Get-ItemProperty 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion').'BuildBranch'")
-build=$(winps_exec "(Get-ItemProperty 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion').'CurrentBuild'")
-full_build=$(winps_exec "(Get-ItemProperty 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion').'BuildLabEx'")
-installdate=$(winps_exec "(Get-ItemProperty 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion').'InstallDate'")
+branch=`$(interop_prefix)c/Windows/System32/reg.exe query "HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion" /v BuildBranch | tail -n 2 | head -n 1`
```
Comment (patrick330602) [inline src/wslsys.sh]: you should trim the `^M` at the very end here(using `sed -e 's|\r||g'`), and also use `$()` instead of ``

Comment (paulstelian97) [reply src/wslsys.sh]: Thanks (didn't notice the ^M that appeared in there; I was using Windows Terminal which apparently doesn't show anything wrong with that).

Comment (patrick330602) [reply src/wslsys.sh]: well, you won't notice the ^M as it is hidden in the output, you have to use `cat -A` to see the character, as it is part of Windows' CRLF

Comment (paulstelian97) [reply src/wslsys.sh]: I see, thanks and thanks for taking care of this. I'll see if I notice something else that might need work. Any idea when this version reaches the repositories?

Comment (patrick330602) [reply src/wslsys.sh]: Once I complete `wslusc` interactive mode, this version will reach the repositories.

Comment (paulstelian97) [reply src/wslsys.sh]: Alright, will see in my free time if I can help. Pretty nice idea, I could use these (the wslfetch banner could be of use, I'll see if I can help with the caching thing)
